name: Deploy Next.js application

on:
  push:
    branches:
      - pipeline

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Build docker image
        run: sudo docker build -t tengoshamugia/kidsfront .
      - name: Login to docker hub
        run: sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASS }}
      - name: Publish image to docker hub
        run: sudo docker push tengoshamugia/kidsfront:latest

  deploy-1:
    needs: build
    runs-on: ["self-hosted", "first"]
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull tengoshamugia/kidsfront:latest
      - name: Delete old container
        run: sudo docker rm -f kidsfront 
      - name: Run docker container
        run: sudo docker run -d -p 3000:3000 --name kidsfront tengoshamugia/kidsfront


  deploy-2:
    needs: build
    runs-on: ["self-hosted", "second"]
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull tengoshamugia/kidsfront:latest
      - name: Delete old container
        run: sudo docker rm -f kidsfront 
      - name: Run docker container
        run: sudo docker run -d -p 3000:3000 --name kidsfront tengoshamugia/kidsfront