name: Deploy Next.js application

on:
  push:
    branches:
      - pipeline

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Build docker image
        run: sudo docker build -t tengoshamugia/kidsfront .
      - name: Login to docker hub
        run: sudo docker login -u "tengoshamugia" -p "Docker.com"
      - name: Publish image to docker hub
        run: sudo docker push tengoshamugia/kidsfront:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull tengoshamugia/kidsfront:latest
      - name: Delete old container
        run: sudo docker rm -f kidsfront 
      - name: Run docker container
        run: sudo docker run -d -p 3000:3000 --name kidsfront tengoshamugia/kidsfront